@ShiftLoggerApi_HostAddress = https://localhost:7225

### Create a new department
POST {{ShiftLoggerApi_HostAddress}}/departments
Content-Type: application/json
Accept: application/json

{
  "DepartmentName": "Accounting"
}

### Create a new worker
POST {{ShiftLoggerApi_HostAddress}}/workers
Content-Type: application/json
Accept: application/json

{
  "FirstName": "Vic",
  "LastName": "Firth",
  "HireDate": "2023-02-15T00:00:00",
  "DepartmentId": 12
}

### Create a new shift
POST {{ShiftLoggerApi_HostAddress}}/shifts
Content-Type: application/json
Accept: application/json

{
  "StartDate": "2025-01-23T08:00:00",
  "EndDate": "2025-01-23T16:00:00",
  "WorkerId": 14
}

### Update a worker (replace {worker_id} with a valid worker ID)
PUT {{ShiftLoggerApi_HostAddress}}/workers/14
Content-Type: application/json
Accept: application/json

{
  "FirstName": "Vic",
  "LastName": "Firth",
  "HireDate": "2022-12-31T00:00:00",
  "DepartmentId": 12
}

### Update a shift (replace {shift_id} with a valid shift ID)
PUT {{ShiftLoggerApi_HostAddress}}/shifts/51
Content-Type: application/json
Accept: application/json

{
  "StartDate": "2025-02-20T07:00:00",
  "EndDate": "2025-02-20T15:00:00",
  "WorkerId": 14
}

### Get all departments
GET {{ShiftLoggerApi_HostAddress}}/departments

### Get a department by ID (replace {department_id} with a valid department ID)
GET {{ShiftLoggerApi_HostAddress}}/departments/1

### Get all shifts
GET {{ShiftLoggerApi_HostAddress}}/shifts

### Get shifts by worker ID (replace {worker_id} with a valid worker ID)
GET {{ShiftLoggerApi_HostAddress}}/shifts/2

### Get shifts by department ID (replace {department_id} with a valid department ID)
GET {{ShiftLoggerApi_HostAddress}}/shifts/department/1

### Get all workers
GET {{ShiftLoggerApi_HostAddress}}/workers

### Get a worker by ID (replace {worker_id} with a valid worker ID)
GET {{ShiftLoggerApi_HostAddress}}/workers/2

### Delete a shift (replace {shift_id} with a valid shift ID)
DELETE {{ShiftLoggerApi_HostAddress}}/shifts/2

### Delete a worker (replace {worker_id} with a valid worker ID)
DELETE {{ShiftLoggerApi_HostAddress}}/workers/5

### Delete a department (replace {department_id} with a valid department ID)
DELETE {{ShiftLoggerApi_HostAddress}}/departments/12
