POST http://localhost:5000/workers
content-type: application/json

{
    "FirstName": "John",
    "LastName": "Doe",
    "Email": "john.doe@csharp.com",
    "Role": "Programmer"
}

###

GET http://localhost:5000/workers/

###

DELETE localhost:5000/workers/1a