// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftsLogger.Ryanw84.Data;

#nullable disable

namespace ShiftsLogger.Ryanw84.Data.Migrations
{
    [DbContext(typeof(ShiftsDbContext))]
    [Migration("20250503204426_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.HasIndex("LocationId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("WorkerId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Location", b =>
                {
                    b.HasOne("ShiftsLogger.Ryanw84.Models.Shift", null)
                        .WithMany("Locations")
                        .HasForeignKey("ShiftId");

                    b.HasOne("ShiftsLogger.Ryanw84.Models.Worker", null)
                        .WithMany("Locations")
                        .HasForeignKey("WorkerId");
                });

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Shift", b =>
                {
                    b.HasOne("ShiftsLogger.Ryanw84.Models.Location", "Location")
                        .WithMany("Shifts")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShiftsLogger.Ryanw84.Models.Worker", "Worker")
                        .WithMany("Shifts")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Worker", b =>
                {
                    b.HasOne("ShiftsLogger.Ryanw84.Models.Shift", null)
                        .WithMany("Workers")
                        .HasForeignKey("ShiftId");
                });

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Location", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Shift", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("ShiftsLogger.Ryanw84.Models.Worker", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
