@ShiftApi_HostAddress = http://localhost:5207

GET {{ShiftApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ShiftApi_HostAddress}}/api/shift/
Accept: application/json

###

PUT {{ShiftApi_HostAddress}}/api/shift/1
Accept: application/json

{

}

###
