// <auto-generated />
using System;
using Buutyful.ShiftsLogger.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buutyful.ShiftsLogger.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240225150405_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buutyful.ShiftsLogger.Domain.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("245645c5-baeb-4196-b635-5ebfd418a4a8"),
                            Duration = new TimeSpan(-288000000002),
                            EndAt = new DateTime(2024, 2, 26, 0, 4, 4, 877, DateTimeKind.Local).AddTicks(1267),
                            ShiftDay = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            StartAt = new DateTime(2024, 2, 25, 16, 4, 4, 877, DateTimeKind.Local).AddTicks(1265),
                            WorkerId = new Guid("6ce80c50-da19-4035-9e7f-3061f20a17e0")
                        });
                });

            modelBuilder.Entity("Buutyful.ShiftsLogger.Domain.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6ce80c50-da19-4035-9e7f-3061f20a17e0"),
                            Name = "Worker1",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("1d2fd51b-5537-489b-98c5-4c5095b832e2"),
                            Name = "Worker2",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("cf037397-311d-4574-a663-05e1af317da8"),
                            Name = "Worker3",
                            Role = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
