// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftsLogger.Lonchanick.ContextDataBase;

#nullable disable

namespace ShiftsLogger.Lonchanick.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20231102011233_intialCreate")]
    partial class intialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftsLogger.Lonchanick.Models.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Check")
                        .HasColumnType("datetime2");

                    b.Property<int>("CheckTypeField")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("Shift", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("85df9217-bc1a-4490-92c9-883b572bc001"),
                            Check = new DateTime(2023, 11, 1, 22, 12, 33, 401, DateTimeKind.Local).AddTicks(7783),
                            CheckTypeField = 0,
                            WorkerId = new Guid("2928fb74-46c1-439c-b8ad-b9aee833fa97")
                        },
                        new
                        {
                            Id = new Guid("85df9217-bc1a-4490-92c9-883b572bc002"),
                            Check = new DateTime(2023, 11, 1, 22, 12, 33, 401, DateTimeKind.Local).AddTicks(7820),
                            CheckTypeField = 0,
                            WorkerId = new Guid("2928fb74-46c1-439c-b8ad-b9aee833fa02")
                        },
                        new
                        {
                            Id = new Guid("85df9217-bc1a-4490-92c9-883b572bc003"),
                            Check = new DateTime(2023, 11, 1, 22, 12, 33, 401, DateTimeKind.Local).AddTicks(7825),
                            CheckTypeField = 0,
                            WorkerId = new Guid("2928fb74-46c1-439c-b8ad-b9aee833fa03")
                        });
                });

            modelBuilder.Entity("ShiftsLogger.Lonchanick.Models.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Worker", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2928fb74-46c1-439c-b8ad-b9aee833fa97"),
                            Name = "Leopoldo"
                        },
                        new
                        {
                            Id = new Guid("2928fb74-46c1-439c-b8ad-b9aee833fa02"),
                            Name = "Ramon"
                        },
                        new
                        {
                            Id = new Guid("2928fb74-46c1-439c-b8ad-b9aee833fa03"),
                            Name = "Trespatines"
                        });
                });

            modelBuilder.Entity("ShiftsLogger.Lonchanick.Models.Shift", b =>
                {
                    b.HasOne("ShiftsLogger.Lonchanick.Models.Worker", "Worker")
                        .WithMany("Shifts")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("ShiftsLogger.Lonchanick.Models.Worker", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
